/**
 * Created by ss on 18/3/3.
 */


export const CHANGE_LOAD_SHOW_STATE = 'CHANGE_LOAD_SHOW_STATE';
export const OPEN_NO_AUTHORIZATION_DIALOG_BOX = 'OPEN_NO_AUTHORIZATION_DIALOG_BOX';
export const CLOSE_OPERATE_DIALOG_BOX = 'CLOSE_OPERATE_DIALOG_BOX';
export const SURE_OPERATE_DIALOG_BOX = 'SURE_OPERATE_DIALOG_BOX';
export const CLOSE_PROMPTD_DIALOG_BOX = 'CLOSE_PROMPTD_DIALOG_BOX';
export const OPEN_OPERATE_DIALOG_BOX = 'OPEN_OPERATE_DIALOG_BOX';
export const SAVE_BLOG_LIST = 'SAVE_BLOG_LIST';
export const SAVE_FLAG_LIST = 'SAVE_FLAG_LIST';
export const OPEN_ERROR_TIP = 'OPEN_ERROR_TIP';
export const CLOSE_ERROR_TIP = 'CLOSE_ERROR_TIP';
export const SAVE_CACHE_ARTICLE_DIST = 'SAVE_CACHE_ARTICLE_DIST';
export const UPDATE_CACHE_ARTICLE_DIST = 'UPDATE_CACHE_ARTICLE_DIST';
export const SAVE_USER_INFO = 'SAVE_USER_INFO'



