/**
 * Created by ss on 18/3/3.
 */


export const CHANGE_LOAD_SHOW_STATE = 'CHANGE_LOAD_SHOW_STATE';
export const OPEN_NO_AUTHORIZATION_DIALOG_BOX = 'OPEN_NO_AUTHORIZATION_DIALOG_BOX';
export const CLOSE_OPERATE_DIALOG_BOX = 'CLOSE_OPERATE_DIALOG_BOX';
export const SURE_OPERATE_DIALOG_BOX = 'SURE_OPERATE_DIALOG_BOX';
export const CLOSE_PROMPTD_DIALOG_BOX = 'CLOSE_PROMPTD_DIALOG_BOX';
export const OPEN_OPERATE_DIALOG_BOX = 'OPEN_OPERATE_DIALOG_BOX';

